// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/pokemon": {
            "get": {
                "description": "Retrieve all Pokemon from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pokemon"
                ],
                "summary": "List all Pokemon",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/pokemon-api_internal_core_domain.Pokemon"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new Pokemon supporting both direct name and nested pokemon.name formats",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pokemon"
                ],
                "summary": "Create a new Pokemon with flexible name format",
                "parameters": [
                    {
                        "description": "Pokemon data with flexible name",
                        "name": "pokemon",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pokemon-api_internal_core_domain.FlexiblePokemonRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/pokemon-api_internal_core_domain.Pokemon"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/pokemon/{id}": {
            "get": {
                "description": "Retrieve a Pokemon by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pokemon"
                ],
                "summary": "Get Pokemon by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pokemon ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pokemon-api_internal_core_domain.Pokemon"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the API is running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "pokemon-api_internal_core_domain.CreatePokemonRequest": {
            "type": "object",
            "required": [
                "name",
                "type1"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "type1": {
                    "type": "string"
                },
                "type2": {
                    "type": "string"
                }
            }
        },
        "pokemon-api_internal_core_domain.FlexiblePokemonRequest": {
            "type": "object",
            "required": [
                "type1"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "pokemon": {
                    "type": "object",
                    "additionalProperties": true
                },
                "type1": {
                    "type": "string"
                },
                "type2": {
                    "type": "string"
                }
            }
        },
        "pokemon-api_internal_core_domain.Pokemon": {
            "type": "object",
            "required": [
                "type1"
            ],
            "properties": {
                "base_experience": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "height": {
                    "description": "External API data (3 additional fields)",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "description": "User-provided basic data (3 fields)",
                    "type": "string"
                },
                "type1": {
                    "type": "string"
                },
                "type2": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "weight": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Pokemon API",
	Description:      "A REST API for managing Pokemon data with PokeAPI integration",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
